# Heavily inspired by Lighthouse: https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/Makefile

GIT_SHA := `git rev-parse HEAD`
GIT_TAG := `git describe --tags --abbrev=0 2>/dev/null || echo "unknown"`
BIN_DIR := "dist/bin"
CARGO_TARGET_DIR := env("CARGO_TARGET_DIR", "target")
FEATURES := env("FEATURES", if os() == "windows" { "asm-keccak min-debug-logs" } else { "jemalloc asm-keccak min-debug-logs" })
PROFILE := env("PROFILE", "release")
CARGO_INSTALL_EXTRA_FLAGS := env("CARGO_INSTALL_EXTRA_FLAGS", "")
DOCKER_IMAGE_NAME := env("DOCKER_IMAGE_NAME", "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-reth")

# default recipe to display help information
default:
  @just --list

# Check for unused dependencies in the crate graph.
check-udeps:
  cargo +nightly udeps --workspace --lib --examples --tests --benches --all-features --locked

# Run unit tests with optional edge storage feature
test edge='':
  #!/usr/bin/env bash
  set -euo pipefail
  RUST_BACKTRACE=1 cargo nextest run \
    --features "asm-keccak {{edge}}" --locked \
    --workspace \
    --no-tests=warn \
    -E "!kind(test) and not binary(e2e_testsuite) and not test(test_online)"

# Run integration tests for reth-optimism-node
test-integration:
  RUST_BACKTRACE=1 cargo nextest run --locked -p reth-optimism-node

# Check Windows cross-compilation
check-windows:
  rustup target add x86_64-pc-windows-gnu
  cargo check -p op-reth --target x86_64-pc-windows-gnu

# Build all examples
examples:
  cargo build --examples --locked

